version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - 'mariadb_data:/bitnami'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MEDIAWIKI_DATABASE_USER=root
      - MEDIAWIKI_DATABASE_NAME=
      - ALLOW_EMPTY_PASSWORD=yes
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mediawiki
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  piwik_data:
    driver: local
