version: '2'
services:
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '81:80'
    volumes:
      - 'piwik_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  piwik_data:
    driver: local