version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - '$PWD/mariadb_data:/bitnami'
  mediawiki:
    restart: always
    depends_on: mariadb
    image: 'smartkit/mediawiki:locale'
    environment:
      - MEDIAWIKI_DATABASE_USER=root
      - MEDIAWIKI_DATABASE_NAME=
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/mediawiki_data:/bitnami'
    depends_on:
      - mariadb
    command: bash -c "/etc/rc.local"
# volumes:
#   $PWD/mariadb_data:
#     driver: local
#   $PWD/mediawiki_data:
#     driver: local